### ISSUE TITLE
AWS bedrock connections not working on latest docker or 0.3-dev docker image

### ISSUE THREAD

**Issue by Chris-Pr** [danswer-ai/danswer#2657]
When creating a new LLM provider for AWS bedrock i receive this error:

Currently working bedrock connections , or new connects do not work on latest version and have the follow error.

 "litellm.APIConnectionError: 'NoneType' object has no attribute 'split' Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/litellm/main.py", line 2413, in completion response = bedrock_converse_chat_completion.completion( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/litellm/llms/bedrock/chat/converse_handler.py", line 320, in completion sigv4.add_auth(request) File "/usr/local/lib/python3.11/site-packages/botocore/auth.py", line 424, in add_auth canonical_request = self.canonical_request(request) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/botocore/auth.py", line 365, in canonical_request cr.append(self.canonical_headers(headers_to_sign) + '\n') ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/botocore/auth.py", line 300, in canonical_headers value = ','.join( ^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/botocore/auth.py", line 301, in <genexpr> self._header_value(v) for v in headers_to_sign.get_all(key) ^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/botocore/auth.py", line 312, in _header_value return ' '.join(value.split()) ^^^^^^^^^^^ AttributeError: 'NoneType' object has no attribute 'split'"

**Comment by rkuo-danswer** [comment]
This may be fixed by https://github.com/danswer-ai/danswer/pull/2649.

**Comment by Chris-Pr** [comment]
This issue still exists.
